<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
   public function run()
{
   Product::insert([
    [
        'name' => 'Hydrating Facial Cleanser',
        'category' => 'Cleanser',
        'image' => 'storage/products/hydrating-facial-cleanser.png',
        'brand' => 'laneige',
        'description' => 'Gentle cleanser that refreshes skin.',
        'ingredients' => 'Water, Glycerin, Ceramides',
        'how_to_use' => 'Massage onto wet skin, rinse well.',
        'price' => 14.99,
        'rating' => 4.5,
        'review_count' => 120,
        'type' => 'Best Seller',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    
 

        [
            'name' => 'Sun Protection SPF 50',
            'category' => 'Sunscreen',
            'image' => 'storage/products/round-lab-sunscreen.webp',
            'brand' => 'cosrx',
            'description' => 'Protects skin from harmful UV rays.',
            'ingredients' => 'Zinc Oxide, Titanium Dioxide',
            'how_to_use' => 'Apply generously before sun exposure.',
            'price' => 19.99,
            'rating' => 4.7,
            'review_count' => 89,
            'type' => 'Best Seller',     
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Refreshing Toner',
            'category' => 'Toner',
            'image' => 'storage/products/balancing-toner.webp',
            'brand' => 'roundlab',
            'description' => 'Balances and refreshes your skin.',
            'ingredients' => 'Aloe Vera, Rose Water',
            'how_to_use' => 'Apply with cotton pad after cleansing.',
            'price' => 12.50,
            'rating' => 4.3,
            'review_count' => 60,
            'type' => 'Best Seller',
            'created_at' => now(),
            'updated_at' => now(),
        ],
         [
            'name' => '3EC Plush',
            'category' => 'Makeup',
            'image' => 'storage/products/3ec-blush.webp',
            'brand' => 'romand',
            'description' => 'A lightweight, buildable blush that delivers a natural flush of color with a silky smooth texture. Perfect for daily wear, it blends effortlessly on the skin and lasts all day.',
            'ingredients' => 'Mica, Talc, Silica, Dimethicone, Magnesium Stearate, Titanium Dioxide, Iron Oxides, Tocopheryl Acetate (Vitamin E), Jojoba Oil, Shea Butter.',
            'how_to_use' => 'Use a blush brush to gently sweep the product onto the apples of your cheeks and blend upward toward your temples. Build color as desired.',
            'price' => 14.99,
            'rating' => 4.6,
            'review_count' => 128,
            'type' => 'Best Seller',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'LumaGlow Brightening Eye Cream',
            'category' => 'Mask',
            'image' => 'storage/products/brightening-eye-cream.webp',
            'brand' => 'romand',
            'description' => 'A gentle yet powerful eye cream designed to reduce the appearance of dark circles, puffiness, and fine lines. Infused with brightening botanicals and peptides to awaken tired eyes.',
            'ingredients' => 'Niacinamide, Caffeine, Hyaluronic Acid, Vitamin C, Peptides, Aloe Vera Extract, Chamomile Extract, Jojoba Oil.',
            'how_to_use' => 'Apply a small amount around the eye area using your ring finger. Gently pat until fully absorbed. Use morning and night.',
            'price' => 22.50,
            'rating' => 4.8,
            'review_count' => 212,
            'type' => 'Best Seller',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'CeraVe Renewing SA Face Exfoliator',
            'category' => 'Mask',
            'image' => 'storage/products/cerave-face-exfoliator.webp',
            'brand' => 'cerave',
            'description' => 'Gentle exfoliating cleanser with salicylic acid that helps exfoliate dead skin cells, smooth rough texture, and maintain the skin’s natural barrier with ceramides.',
            'ingredients' => 'Salicylic Acid, Niacinamide, Ceramides (1, 3, 6-II), Hyaluronic Acid, Water, Glycerin, Cetearyl Alcohol.',
            'how_to_use' => 'Wet face, then apply the cleanser with fingertips. Gently massage in a circular motion, then rinse thoroughly. Use once daily or as directed.',
            'price' => 13.99,
            'rating' => 4.7,
            'review_count' => 354,
            'type' => 'Best Seller',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'COSRX Low pH Good Morning Gel Cleanser',
            'category' => 'Cleanser',
            'image' => 'storage/products/cosrx-gel-cleanser.webp',
            'brand' => 'cosrx',
            'description' => 'A gentle gel cleanser formulated with a low pH to maintain skin’s balance. Perfect for morning use, it removes impurities without stripping the skin, leaving it fresh and hydrated.',
            'ingredients' => 'Purified Water, Cocamidopropyl Betaine, Sodium Lauroyl Methyl Isethionate, Saccharomyces Ferment, Tea Tree Leaf Oil, Betaine Salicylate, Allantoin.',
            'how_to_use' => 'Apply to damp face and massage gently in a circular motion. Rinse off with lukewarm water. Use every morning and evening.',
            'price' => 11.50,
            'rating' => 4.9,
            'review_count' => 489,
            'type' => 'Best Seller',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'COSRX Aloe Soothing Sun Cream SPF50+ PA+++',
            'category' => 'Sunscreen',
            'image' => 'storage/products/cosrx-sunscreen.webp',
            'brand' => 'cosrx',
            'description' => 'A lightweight, moisturizing sunscreen that provides broad-spectrum protection with SPF50+ PA+++. Infused with aloe vera to soothe and hydrate skin while protecting it from harmful UV rays.',
            'ingredients' => 'Aloe Barbadensis Leaf Extract, Ethylhexyl Methoxycinnamate, Butylene Glycol, Glycerin, Titanium Dioxide, Zinc Oxide, Dimethicone.',
            'how_to_use' => 'Apply a generous amount as the final step in your skincare routine. Reapply every 2 hours when exposed to sunlight.',
            'price' => 15.99,
            'rating' => 4.8,
            'review_count' => 376,
            'type' => 'Best Seller',
            'created_at' => now(),
            'updated_at' => now(),
        ],
[
    'name' => 'LumaGlow Daily Moisturizer SPF 30',
    'category' => 'Moisturizer',
    'image' => 'storage/products/daily-moisturizer-spf30.jpeg',
    'brand' => 'roundlab',
    'description' => 'A lightweight, non-greasy daily moisturizer with broad-spectrum SPF 30 protection. Hydrates and nourishes the skin while defending against harmful UV rays and premature aging.',
    'ingredients' => 'Hyaluronic Acid, Niacinamide, Glycerin, Octinoxate, Avobenzone, Aloe Vera Extract, Vitamin E, Ceramides.',
    'how_to_use' => 'Apply evenly to the face and neck every morning as the last step in your skincare routine. Reapply as needed during sun exposure.',
    'price' => 17.99,
    'rating' => 4.5,
    'review_count' => 198,
    'type' => 'Best Seller',
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'name' => 'Dove Hair Color Protect Shampoo',
    'category' => 'Haircare',
    'image' => 'storage/products/dove-hair-color-protect.jpg',
    'brand' => 'Dove',
    'description' => 'A gentle shampoo specially formulated to protect and nourish color-treated hair. Helps maintain vibrant color while leaving hair soft, smooth, and shiny.',
    'ingredients' => 'Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Glycerin, Dimethiconol, Arginine, Keratin, Fragrance, Citric Acid.',
    'how_to_use' => 'Apply to wet hair, massage into a rich lather, and rinse thoroughly. For best results, follow with Dove Color Protect Conditioner.',
    'price' => 8.99,
    'rating' => 4.4,
    'review_count' => 143,
    'type' => 'Best Seller',
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'name' => 'Dove Daily Moisture Conditioner',
    'category' => 'Haircare',
    'image' => 'storage/products/dove-hair-conditioner.webp',
    'brand' => 'Dove',
    'description' => 'A nourishing conditioner that helps protect hair from daily wear and tear. Formulated with Pro-Moisture Complex to deeply nourish and smooth hair, leaving it soft, manageable, and healthy-looking.',
    'ingredients' => 'Water, Cetearyl Alcohol, Behentrimonium Chloride, Dimethicone, Glycerin, Fragrance, Lactic Acid, Arginine, Sunflower Seed Oil.',
    'how_to_use' => 'After shampooing, apply to mid-lengths and ends of wet hair. Leave on for 1–3 minutes, then rinse thoroughly.',
    'price' => 7.49,
    'rating' => 4.5,
    'review_count' => 165,
    'type' => 'Promotion',
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'name' => 'Dove Exfoliating Body Scrub – Crushed Macadamia & Rice Milk',
    'category' => 'Bodycare',
    'image' => 'storage/products/dove-scrub.avif',
    'brand' => 'Dove',
    'description' => 'A creamy, whipped body scrub that gently exfoliates to remove dull, dry skin while nourishing deeply with moisturizing ingredients. Leaves skin soft, smooth, and glowing after every use.',
    'ingredients' => 'Water, Glycerin, Stearic Acid, Palmitic Acid, Macadamia Seed Powder, Rice Milk Extract, Fragrance, Sodium Hydroxide.',
    'how_to_use' => 'Scoop a generous amount and gently massage over wet skin in circular motions. Rinse thoroughly. Use 3–4 times per week for best results.',
    'price' => 9.99,
    'rating' => 4.7,
    'review_count' => 232,
    'type' => 'Promotion',
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'name' => 'LumaGlow Exfoliating Facial Scrub',
    'category' => 'Bodycare',
    'image' => 'storage/products/exfoliating-facial-scrub.webp',
    'brand' => 'roundlab',
    'description' => 'A gentle yet effective facial scrub that buffs away dead skin cells, unclogs pores, and reveals a smoother, brighter complexion. Formulated with natural exfoliants and hydrating botanicals.',
    'ingredients' => 'Water, Walnut Shell Powder, Glycerin, Aloe Vera, Green Tea Extract, Vitamin E, Jojoba Oil, Citric Acid, Fragrance.',
    'how_to_use' => 'Apply to damp face and gently massage in circular motions, avoiding the eye area. Rinse thoroughly with lukewarm water. Use 2–3 times a week.',
    'price' => 12.49,
    'rating' => 4.6,
    'review_count' => 179,
    'type' => 'Promotion',
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'name' => 'Garnier Skin Naturals Face Mask',
    'category' => 'Mask',
    'image' => 'storage/products/garnier-skin-naturals-face-mask.webp',
    'brand' => 'romand',
    'description' => 'A hydrating and refreshing face mask formulated with natural ingredients to nourish and brighten your skin. Suitable for all skin types and perfect for weekly pampering sessions.',
    'ingredients' => 'Water, Glycerin, Kaolin, Aloe Vera Extract, Green Tea Extract, Vitamin C, Fragrance.',
    'how_to_use' => 'Apply evenly on clean face, avoiding the eye area. Leave on for 10–15 minutes, then rinse thoroughly with lukewarm water. Use 1–2 times per week.',
    'price' => 6.99,
    'rating' => 4.3,
    'review_count' => 215,
    'type' => 'Promotion',
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'name' => 'LumaGlow Hydrating Face Mask',
    'category' => 'Mask',
    'image' => 'storage/products/hydrating-face-mask.webp',
    'brand' => 'romand',
    'description' => 'A nourishing hydrating face mask infused with hyaluronic acid and aloe vera to deeply moisturize and revitalize dry, dull skin. Leaves your skin feeling soft, plump, and refreshed.',
    'ingredients' => 'Hyaluronic Acid, Aloe Vera Extract, Glycerin, Vitamin E, Panthenol, Chamomile Extract, Water.',
    'how_to_use' => 'Apply an even layer on cleansed face, avoiding the eye area. Leave on for 15–20 minutes, then rinse or gently pat remaining serum into the skin. Use 2–3 times per week.',
    'price' => 14.99,
    'rating' => 4.7,
    'review_count' => 134,
    'type' => 'Promotion',
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'name' => 'LumaGlow Hydrating Facial Cleanser',
    'category' => 'Cleanser',
    'image' => 'storage/products/hydrating-facial-cleanser.png',
    'brand' => 'cerave',
    'description' => 'A gentle, moisturizing facial cleanser that removes impurities without stripping the skin’s natural moisture. Enriched with soothing ingredients to leave skin soft and refreshed.',
    'ingredients' => 'Glycerin, Aloe Vera Extract, Hyaluronic Acid, Panthenol, Chamomile Extract, Water, Cocamidopropyl Betaine.',
    'how_to_use' => 'Apply to damp face, gently massage in circular motions, then rinse thoroughly with lukewarm water. Use morning and night.',
    'price' => 13.50,
    'rating' => 4.6,
    'review_count' => 210,
    'type' => 'Promotion',
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'name' => 'Jumiso Vitamin C Brightening Serum',
    'category' => 'Serum',
    'image' => 'storage/products/jumiso-brightening-serum.webp',
    'brand' => 'laneige',
    'description' => 'A potent brightening serum formulated with Vitamin C and botanical extracts to even skin tone, reduce dark spots, and enhance radiance. Lightweight and fast-absorbing.',
    'ingredients' => 'Ascorbic Acid (Vitamin C), Niacinamide, Aloe Vera Extract, Green Tea Extract, Hyaluronic Acid, Glycerin.',
    'how_to_use' => 'Apply a few drops to clean face and neck after cleansing and toning. Use morning and night for best results.',
    'price' => 21.99,
    'rating' => 4.7,
    'review_count' => 142,
    'type' => 'Promotion',
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'name' => 'Nivea Aloe Vera Body Lotion',
    'category' => 'Lotion',
    'image' => 'storage/products/nivea-aloe-vera-lotion.webp',
    'brand' => 'nivea',
    'description' => 'A refreshing and moisturizing body lotion enriched with aloe vera extract. Provides long-lasting hydration and soothes dry, sensitive skin, leaving it soft and smooth.',
    'ingredients' => 'Water, Glycerin, Aloe Barbadensis Leaf Extract, Paraffinum Liquidum, Panthenol, Tocopheryl Acetate (Vitamin E), Fragrance.',
    'how_to_use' => 'Apply generously to the entire body after showering or whenever skin feels dry. Massage until fully absorbed.',
    'price' => 9.99,
    'rating' => 4.5,
    'review_count' => 198,
    'type' => 'Promotion',
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'name' => 'LumaGlow Nourishing Night Cream',
    'category' => 'Lotion',
    'image' => 'storage/products/nourishing-night-cream.avif',
    'brand' => 'nivea',
    'description' => 'A rich and hydrating night cream formulated to deeply nourish and repair skin overnight. Contains antioxidants and moisturizing ingredients to rejuvenate and restore skin\'s natural glow.',
    'ingredients' => 'Shea Butter, Jojoba Oil, Vitamin E, Hyaluronic Acid, Niacinamide, Ceramides, Aloe Vera Extract.',
    'how_to_use' => 'Apply evenly to clean face and neck every evening as the last step in your skincare routine. Massage gently until fully absorbed.',
    'price' => 19.99,
    'rating' => 4.7,
    'review_count' => 156,
    'type' => 'Promotion',
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'name' => 'LumaGlow Pimple Patches',
    'category' => 'Exfloliator',
    'image' => 'storage/products/pimple-patches.jpg',
    'brand' => 'nivea',
    'description' => 'Hydrocolloid pimple patches that help reduce inflammation and protect blemishes from dirt and bacteria. Invisible and easy to use, they promote faster healing of pimples.',
    'ingredients' => 'Hydrocolloid, Aloe Vera Extract, Tea Tree Oil, Centella Asiatica Extract.',
    'how_to_use' => 'Clean and dry the affected area. Apply patch directly onto the pimple and leave on for 6–8 hours or overnight. Remove gently and discard.',
    'price' => 6.50,
    'rating' => 4.5,
    'review_count' => 312,
    'type' => 'Promotion',
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'name' => 'Romand Blur Fudge Tint',
    'category' => 'Makeup',
    'image' => 'storage/products/romand-blur-fudge-tint.webp',
    'brand' => 'romand',
    'description' => 'A soft and velvety lip tint with a blurred, matte finish that provides long-lasting color without drying out the lips. Perfect for a natural, everyday look.',
    'ingredients' => 'Isododecane, Cyclopentasiloxane, Trimethylsiloxysilicate, Synthetic Wax, Tocopheryl Acetate (Vitamin E), Fragrance.',
    'how_to_use' => 'Apply directly to lips using the applicator. Layer for more intense color. Reapply as needed throughout the day.',
    'price' => 12.00,
    'rating' => 4.4,
    'review_count' => 89,
    'type' => 'Trending',
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'name' => 'Romand Juicy Lasting Tint',
    'category' => 'Makeup',
    'image' => 'storage/products/romand-juicy-lasting-tint.webp',
    'brand' => 'romand',
    'description' => 'A juicy, moisturizing lip tint that delivers vibrant color with a glossy finish. Long-lasting formula that keeps lips hydrated and fresh throughout the day.',
    'ingredients' => 'Water, Dimethicone, Glycerin, Isododecane, Tocopheryl Acetate (Vitamin E), Fragrance, Synthetic Fluorphlogopite.',
    'how_to_use' => 'Apply evenly on lips using the applicator. Reapply for a more intense look or whenever needed.',
    'price' => 13.50,
    'rating' => 4.5,
    'review_count' => 102,
    'type' => 'Trending',
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'name' => 'Romand Volume Boost Mascara',
    'category' => 'Makeup',
    'image' => 'storage/products/romand-mascara.webp',
    'brand' => 'romand',
    'description' => 'A volumizing mascara that lifts and thickens lashes for a dramatic, full look. Smudge-proof and long-lasting formula that keeps lashes defined all day.',
    'ingredients' => 'Water, Beeswax, Carnauba Wax, Paraffin, Iron Oxides, Synthetic Beeswax, Panthenol (Vitamin B5), Tocopherol (Vitamin E).',
    'how_to_use' => 'Apply from the roots to the tips of lashes in a zigzag motion. Apply multiple coats for extra volume. Remove with makeup remover.',
    'price' => 15.00,
    'rating' => 4.6,
    'review_count' => 97,
    'type' => 'Trending',
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'name' => 'Round Lab Hydrating Cleanser',
    'category' => 'Exfloliator',
    'image' => 'storage/products/round-lab-cleanser.webp',
    'brand' => 'roundlab',
    'description' => 'A gentle hydrating cleanser that effectively removes impurities while maintaining the skin’s natural moisture balance. Ideal for sensitive and dry skin types.',
    'ingredients' => 'Water, Glycerin, Sodium Cocoyl Glycinate, Centella Asiatica Extract, Panthenol, Betaine, Ceramide NP.',
    'how_to_use' => 'Apply a small amount to damp face, gently massage in circular motions, then rinse thoroughly with lukewarm water. Use morning and night.',
    'price' => 18.50,
    'rating' => 4.7,
    'review_count' => 140,
    'type' => 'Trending',
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'name' => 'Round Lab Soothing Face Mask',
    'category' => 'Exfloliator',
    'image' => 'storage/products/round-lab-face-mask.jpg',
    'brand' => 'roundlab',
    'description' => 'A soothing sheet mask infused with Centella Asiatica extract to calm irritated and sensitive skin, providing deep hydration and a refreshed complexion.',
    'ingredients' => 'Water, Centella Asiatica Extract, Glycerin, Sodium Hyaluronate, Panthenol, Allantoin.',
    'how_to_use' => 'Apply the mask to cleansed face, leave on for 15–20 minutes, then remove and gently pat remaining essence into the skin.',
    'price' => 4.99,
    'rating' => 4.5,
    'review_count' => 85,
    'type' => 'Trending',
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'name' => 'Round Lab Daily Sunscreen SPF50+ PA++++',
    'category' => 'Exfloliator',
    'image' => 'storage/products/round-lab-sunscreen.webp',
    'brand' => 'roundlab',
    'description' => 'A lightweight, non-greasy sunscreen that provides high protection against UVA and UVB rays. Enriched with soothing botanical extracts to calm and hydrate skin.',
    'ingredients' => 'Zinc Oxide, Titanium Dioxide, Aloe Vera Extract, Centella Asiatica Extract, Glycerin, Panthenol.',
    'how_to_use' => 'Apply generously to face and neck 15 minutes before sun exposure. Reapply every 2 hours or after sweating/swimming.',
    'price' => 22.00,
    'rating' => 4.6,
    'review_count' => 120,
    'type' => 'Trending',
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'name' => 'Round Lab Hydrating Toner',
    'category' => 'Toner',
    'image' => 'storage/products/round-lab-toner.webp',
    'brand' => 'roundlab',
    'description' => 'A refreshing toner that deeply hydrates and soothes the skin with Centella Asiatica extract and hyaluronic acid. Prepares skin for better absorption of serums and moisturizers.',
    'ingredients' => 'Water, Centella Asiatica Extract, Glycerin, Sodium Hyaluronate, Panthenol, Allantoin.',
    'how_to_use' => 'After cleansing, apply toner to a cotton pad or hands and gently pat onto face and neck. Use morning and night.',
    'price' => 17.50,
    'rating' => 4.7,
    'review_count' => 130,
    'type' => 'Trending',
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'name' => 'Skin1004 Madagascar Centella Sun Serum SPF50+ PA++++',
    'category' => 'Serum',
    'image' => 'storage/products/skin1004-sunserum.webp',
    'brand' => 'laneige',
    'description' => 'A lightweight sun serum with high SPF protection enriched with Centella Asiatica extract to soothe and hydrate skin while protecting against UV rays.',
    'ingredients' => 'Centella Asiatica Extract, Titanium Dioxide, Zinc Oxide, Niacinamide, Glycerin, Panthenol.',
    'how_to_use' => 'Apply evenly on face and neck 15 minutes before sun exposure. Reapply every 2 hours, especially after sweating or swimming.',
    'price' => 20.99,
    'rating' => 4.8,
    'review_count' => 150,
    'type' => 'Trending',
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'name' => 'Star Brightening Face Cream',
    'category' => 'Mask',
    'image' => 'storage/products/star-face.avif',
    'brand' => 'Star Cosmetics',
    'description' => 'A nourishing brightening face cream that helps even skin tone and restore radiance with natural botanical extracts. Lightweight and suitable for daily use.',
    'ingredients' => 'Niacinamide, Vitamin C, Aloe Vera Extract, Shea Butter, Jojoba Oil, Hyaluronic Acid.',
    'how_to_use' => 'Apply a small amount to cleansed face and neck every morning and evening. Massage gently until fully absorbed.',
    'price' => 16.75,
    'rating' => 4.4,
    'review_count' => 112,
    'type' => 'Trending',
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'name' => 'Tree Hut Shea Sugar Scrub',
    'category' => 'Bodycare',
    'image' => 'storage/products/tree-hut-body-scrub.webp',
    'brand' => 'Tree Hut',
    'description' => 'An exfoliating body scrub made with natural shea butter and sugar crystals that gently removes dead skin cells while deeply moisturizing, leaving skin soft and smooth.',
    'ingredients' => 'Sugar, Shea Butter, Almond Oil, Jojoba Oil, Vitamin E, Coconut Oil, Fragrance.',
    'how_to_use' => 'Apply to damp skin in circular motions, focusing on rough areas. Rinse thoroughly. Use 2-3 times a week for best results.',
    'price' => 12.99,
    'rating' => 4.7,
    'review_count' => 220,
    'type' => 'Trending',
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'name' => 'Vaseline Intensive Care Lotion',
    'category' => 'Bodycare',
    'image' => 'storage/products/vaseline-lotion.jpg',
    'brand' => 'Vaseline',
    'description' => 'A fast-absorbing lotion that deeply moisturizes and heals dry skin. Formulated with microdroplets of Vaseline Jelly to lock in moisture and protect skin’s natural barrier.',
    'ingredients' => 'Petrolatum, Glycerin, Mineral Oil, Dimethicone, Fragrance.',
    'how_to_use' => 'Apply liberally to dry skin as needed, especially after bathing or washing hands.',
    'price' => 8.99,
    'rating' => 4.5,
    'review_count' => 350,
    'type' => 'Essential',
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'name' => 'Vitamin C Brightening Serum',
    'category' => 'Serum',
    'image' => 'storage/products/vitamin-c-brightening-serum.webp',
    'brand' => 'LumaGlow',
    'description' => 'A potent brightening serum enriched with Vitamin C and antioxidants to help reduce dark spots, even skin tone, and boost radiance.',
    'ingredients' => 'Ascorbic Acid (Vitamin C), Hyaluronic Acid, Niacinamide, Vitamin E, Aloe Vera Extract.',
    'how_to_use' => 'Apply a few drops to cleansed face and neck in the morning and evening. Follow with moisturizer and sunscreen during the day.',
    'price' => 24.99,
    'rating' => 4.8,
    'review_count' => 210,
    'type' => 'Best Seller',
    'created_at' => now(),
    'updated_at' => now(),
],


    ]);
}

}
